obj-$(CONFIG_EXYNOS_DECON_LCD) += dsim_panel.o
obj-$(CONFIG_EXYNOS_DECON_MDNIE_LITE) += mdnie_lite.o mdnie_tuning.o

obj-$(CONFIG_PANEL_S6E8AA5X01)	+= s6e8aa5x01_lcd_ctrl.o dimming_core.o
obj-$(CONFIG_PANEL_TD4100)	+= td4100_lcd_ctrl.o
