/****************************************************************************
 *
 *       Internal BT driver HCI decoder
 *
 *       Copyright (c) 2015 Samsung Electronics Co., Ltd
 *
 ****************************************************************************/

#ifndef __SCSC_BT_HCI_H
#define __SCSC_BT_HCI_H

#define HCI_EVENT_HEADER_LENGTH                      (2)

#define HCI_LINK                                     ((u16)0x0400)
#define HCI_POLICY                                   ((u16)0x0800)
#define HCI_HOST_BB                                  ((u16)0x0C00)
#define HCI_INFO                                     ((u16)0x1000)
#define HCI_STATUS                                   ((u16)0x1400)
#define HCI_TEST                                     ((u16)0x1800)
#define HCI_ULP                                      ((u16)0x2000)

#define HCI_INQUIRY                                                 ((u16)HCI_LINK | 0x0001)
#define HCI_INQUIRY_CANCEL                                          ((u16)HCI_LINK | 0x0002)
#define HCI_PERIODIC_INQUIRY_MODE                                   ((u16)HCI_LINK | 0x0003)
#define HCI_EXIT_PERIODIC_INQUIRY_MODE                              ((u16)HCI_LINK | 0x0004)
#define HCI_CREATE_CONNECTION                                       ((u16)HCI_LINK | 0x0005)
#define HCI_DISCONNECT                                              ((u16)HCI_LINK | 0x0006)
#define HCI_ADD_SCO_CONNECTION                                      ((u16)HCI_LINK | 0x0007)
#define HCI_CREATE_CONNECTION_CANCEL                                ((u16)HCI_LINK | 0x0008)
#define HCI_ACCEPT_CONNECTION_REQ                                   ((u16)HCI_LINK | 0x0009)
#define HCI_REJECT_CONNECTION_REQ                                   ((u16)HCI_LINK | 0x000A)
#define HCI_LINK_KEY_REQ_REPLY                                      ((u16)HCI_LINK | 0x000B)
#define HCI_LINK_KEY_REQ_NEG_REPLY                                  ((u16)HCI_LINK | 0x000C)
#define HCI_PIN_CODE_REQ_REPLY                                      ((u16)HCI_LINK | 0x000D)
#define HCI_PIN_CODE_REQ_NEG_REPLY                                  ((u16)HCI_LINK | 0x000E)
#define HCI_CHANGE_CONN_PKT_TYPE                                    ((u16)HCI_LINK | 0x000F)
#define HCI_AUTH_REQ                                                ((u16)HCI_LINK | 0x0011)
#define HCI_SET_CONN_ENCRYPTION                                     ((u16)HCI_LINK | 0x0013)
#define HCI_CHANGE_CONN_LINK_KEY                                    ((u16)HCI_LINK | 0x0015)
#define HCI_MASTER_LINK_KEY                                         ((u16)HCI_LINK | 0x0017)
#define HCI_REMOTE_NAME_REQ                                         ((u16)HCI_LINK | 0x0019)
#define HCI_REMOTE_NAME_REQ_CANCEL                                  ((u16)HCI_LINK | 0x001A)
#define HCI_READ_REMOTE_SUPP_FEATURES                               ((u16)HCI_LINK | 0x001B)
#define HCI_READ_REMOTE_EXT_FEATURES                                ((u16)HCI_LINK | 0x001C)
#define HCI_READ_REMOTE_VER_INFO                                    ((u16)HCI_LINK | 0x001D)
#define HCI_READ_CLOCK_OFFSET                                       ((u16)HCI_LINK | 0x001F)
#define HCI_READ_LMP_HANDLE                                         ((u16)HCI_LINK | 0x0020)
#define HCI_EXCHANGE_FIXED_INFO                                     ((u16)HCI_LINK | 0x0021)
#define HCI_EXCHANGE_ALIAS_INFO                                     ((u16)HCI_LINK | 0x0022)
#define HCI_PRIVATE_PAIRING_REQ_REPLY                               ((u16)HCI_LINK | 0x0023)
#define HCI_PRIVATE_PAIRING_REQ_NEG_REPLY                           ((u16)HCI_LINK | 0x0024)
#define HCI_GENERATED_ALIAS                                         ((u16)HCI_LINK | 0x0025)
#define HCI_ALIAS_ADDRESS_REQ_REPLY                                 ((u16)HCI_LINK | 0x0026)
#define HCI_ALIAS_ADDRESS_REQ_NEG_REPLY                             ((u16)HCI_LINK | 0x0027)
#define HCI_SETUP_SYNCHRONOUS_CONN                                  ((u16)HCI_LINK | 0x0028)
#define HCI_ACCEPT_SYNCHRONOUS_CONN_REQ                             ((u16)HCI_LINK | 0x0029)
#define HCI_REJECT_SYNCHRONOUS_CONN_REQ                             ((u16)HCI_LINK | 0x002A)
#define HCI_IO_CAPABILITY_REQUEST_REPLY                             ((u16)HCI_LINK | 0x002B)
#define HCI_USER_CONFIRMATION_REQUEST_REPLY                         ((u16)HCI_LINK | 0x002C)
#define HCI_USER_CONFIRMATION_REQUEST_NEG_REPLY                     ((u16)HCI_LINK | 0x002D)
#define HCI_USER_PASSKEY_REQUEST_REPLY                              ((u16)HCI_LINK | 0x002E)
#define HCI_USER_PASSKEY_REQUEST_NEG_REPLY                          ((u16)HCI_LINK | 0x002F)
#define HCI_REMOTE_OOB_DATA_REQUEST_REPLY                           ((u16)HCI_LINK | 0x0030)
#define HCI_REMOTE_OOB_DATA_REQUEST_NEG_REPLY                       ((u16)HCI_LINK | 0x0033)
#define HCI_IO_CAPABILITY_REQUEST_NEG_REPLY                         ((u16)HCI_LINK | 0x0034)
#define HCI_ENHANCED_SETUP_SYNC_CONN                                ((u16)HCI_LINK | 0x003D)
#define HCI_ENHANCED_ACCEPT_SYNC_CONN_REQ                           ((u16)HCI_LINK | 0x003E)
#define HCI_TRUNCATED_PAGE                                          ((u16)HCI_LINK | 0x003F)
#define HCI_TRUNCATED_PAGE_CANCEL                                   ((u16)HCI_LINK | 0x0040)
#define HCI_SET_CSB                                                 ((u16)HCI_LINK | 0x0041)
#define HCI_SET_CSB_RECEIVE                                         ((u16)HCI_LINK | 0x0042)
#define HCI_START_SYNCHRONIZATION_TRAIN                             ((u16)HCI_LINK | 0x0043)
#define HCI_RECEIVE_SYNCHRONIZATION_TRAIN                           ((u16)HCI_LINK | 0x0044)
#define HCI_REMOTE_OOB_EXTENDED_DATA_REQUEST_REPLY                  ((u16)HCI_LINK | 0x0045)
#define HCI_HOLD_MODE                                               ((u16)HCI_POLICY | 0x0001)
#define HCI_SNIFF_MODE                                              ((u16)HCI_POLICY | 0x0003)
#define HCI_EXIT_SNIFF_MODE                                         ((u16)HCI_POLICY | 0x0004)
#define HCI_PARK_MODE                                               ((u16)HCI_POLICY | 0x0005)
#define HCI_EXIT_PARK_MODE                                          ((u16)HCI_POLICY | 0x0006)
#define HCI_QOS_SETUP                                               ((u16)HCI_POLICY | 0x0007)
#define HCI_ROLE_DISCOVERY                                          ((u16)HCI_POLICY | 0x0009)
#define HCI_SWITCH_ROLE                                             ((u16)HCI_POLICY | 0x000B)
#define HCI_READ_LINK_POLICY_SETTINGS                               ((u16)HCI_POLICY | 0x000C)
#define HCI_WRITE_LINK_POLICY_SETTINGS                              ((u16)HCI_POLICY | 0x000D)
#define HCI_READ_DEFAULT_LINK_POLICY_SETTINGS                       ((u16)HCI_POLICY | 0x000E)
#define HCI_WRITE_DEFAULT_LINK_POLICY_SETTINGS                      ((u16)HCI_POLICY | 0x000F)
#define HCI_FLOW_SPEC                                               ((u16)HCI_POLICY | 0x0010)
#define HCI_SNIFF_SUB_RATE                                          ((u16)HCI_POLICY | 0x0011)
#define HCI_SET_EVENT_MASK                                          ((u16)HCI_HOST_BB | 0x0001)
#define HCI_RESET                                                   ((u16)HCI_HOST_BB | 0x0003)
#define HCI_SET_EVENT_FILTER                                        ((u16)HCI_HOST_BB | 0x0005)
#define HCI_FLUSH                                                   ((u16)HCI_HOST_BB | 0x0008)
#define HCI_READ_PIN_TYPE                                           ((u16)HCI_HOST_BB | 0x0009)
#define HCI_WRITE_PIN_TYPE                                          ((u16)HCI_HOST_BB | 0x000A)
#define HCI_CREATE_NEW_UNIT_KEY                                     ((u16)HCI_HOST_BB | 0x000B)
#define HCI_READ_STORED_LINK_KEY                                    ((u16)HCI_HOST_BB | 0x000D)
#define HCI_WRITE_STORED_LINK_KEY                                   ((u16)HCI_HOST_BB | 0x0011)
#define HCI_DELETE_STORED_LINK_KEY                                  ((u16)HCI_HOST_BB | 0x0012)
#define HCI_CHANGE_LOCAL_NAME                                       ((u16)HCI_HOST_BB | 0x0013)
#define HCI_READ_LOCAL_NAME                                         ((u16)HCI_HOST_BB | 0x0014)
#define HCI_READ_CONN_ACCEPT_TIMEOUT                                ((u16)HCI_HOST_BB | 0x0015)
#define HCI_WRITE_CONN_ACCEPT_TIMEOUT                               ((u16)HCI_HOST_BB | 0x0016)
#define HCI_READ_PAGE_TIMEOUT                                       ((u16)HCI_HOST_BB | 0x0017)
#define HCI_WRITE_PAGE_TIMEOUT                                      ((u16)HCI_HOST_BB | 0x0018)
#define HCI_READ_SCAN_ENABLE                                        ((u16)HCI_HOST_BB | 0x0019)
#define HCI_WRITE_SCAN_ENABLE                                       ((u16)HCI_HOST_BB | 0x001A)
#define HCI_READ_PAGESCAN_ACTIVITY                                  ((u16)HCI_HOST_BB | 0x001B)
#define HCI_WRITE_PAGESCAN_ACTIVITY                                 ((u16)HCI_HOST_BB | 0x001C)
#define HCI_READ_INQUIRYSCAN_ACTIVITY                               ((u16)HCI_HOST_BB | 0x001D)
#define HCI_WRITE_INQUIRYSCAN_ACTIVITY                              ((u16)HCI_HOST_BB | 0x001E)
#define HCI_READ_AUTH_ENABLE                                        ((u16)HCI_HOST_BB | 0x001F)
#define HCI_WRITE_AUTH_ENABLE                                       ((u16)HCI_HOST_BB | 0x0020)
#define HCI_READ_ENC_MODE                                           ((u16)HCI_HOST_BB | 0x0021)
#define HCI_WRITE_ENC_MODE                                          ((u16)HCI_HOST_BB | 0x0022)
#define HCI_READ_CLASS_OF_DEVICE                                    ((u16)HCI_HOST_BB | 0x0023)
#define HCI_WRITE_CLASS_OF_DEVICE                                   ((u16)HCI_HOST_BB | 0x0024)
#define HCI_READ_VOICE_SETTING                                      ((u16)HCI_HOST_BB | 0x0025)
#define HCI_WRITE_VOICE_SETTING                                     ((u16)HCI_HOST_BB | 0x0026)
#define HCI_READ_AUTO_FLUSH_TIMEOUT                                 ((u16)HCI_HOST_BB | 0x0027)
#define HCI_WRITE_AUTO_FLUSH_TIMEOUT                                ((u16)HCI_HOST_BB | 0x0028)
#define HCI_READ_NUM_BCAST_RETXS                                    ((u16)HCI_HOST_BB | 0x0029)
#define HCI_WRITE_NUM_BCAST_RETXS                                   ((u16)HCI_HOST_BB | 0x002A)
#define HCI_READ_HOLD_MODE_ACTIVITY                                 ((u16)HCI_HOST_BB | 0x002B)
#define HCI_WRITE_HOLD_MODE_ACTIVITY                                ((u16)HCI_HOST_BB | 0x002C)
#define HCI_READ_TX_POWER_LEVEL                                     ((u16)HCI_HOST_BB | 0x002D)
#define HCI_READ_SCO_FLOW_CON_ENABLE                                ((u16)HCI_HOST_BB | 0x002E)
#define HCI_WRITE_SCO_FLOW_CON_ENABLE                               ((u16)HCI_HOST_BB | 0x002F)
#define HCI_SET_HCTOHOST_FLOW_CONTROL                               ((u16)HCI_HOST_BB | 0x0031)
#define HCI_HOST_BUFFER_SIZE                                        ((u16)HCI_HOST_BB | 0x0033)
#define HCI_HOST_NUM_COMPLETED_PACKETS                              ((u16)HCI_HOST_BB | 0x0035)
#define HCI_READ_LINK_SUPERV_TIMEOUT                                ((u16)HCI_HOST_BB | 0x0036)
#define HCI_WRITE_LINK_SUPERV_TIMEOUT                               ((u16)HCI_HOST_BB | 0x0037)
#define HCI_READ_NUM_SUPPORTED_IAC                                  ((u16)HCI_HOST_BB | 0x0038)
#define HCI_READ_CURRENT_IAC_LAP                                    ((u16)HCI_HOST_BB | 0x0039)
#define HCI_WRITE_CURRENT_IAC_LAP                                   ((u16)HCI_HOST_BB | 0x003A)
#define HCI_READ_PAGESCAN_PERIOD_MODE                               ((u16)HCI_HOST_BB | 0x003B)
#define HCI_WRITE_PAGESCAN_PERIOD_MODE                              ((u16)HCI_HOST_BB | 0x003C)
#define HCI_READ_PAGESCAN_MODE                                      ((u16)HCI_HOST_BB | 0x003D)
#define HCI_WRITE_PAGESCAN_MODE                                     ((u16)HCI_HOST_BB | 0x003E)
#define HCI_SET_AFH_CHANNEL_CLASS                                   ((u16)HCI_HOST_BB | 0x003F)
#define HCI_READ_INQUIRY_SCAN_TYPE                                  ((u16)HCI_HOST_BB | 0x0042)
#define HCI_WRITE_INQUIRY_SCAN_TYPE                                 ((u16)HCI_HOST_BB | 0x0043)
#define HCI_READ_INQUIRY_MODE                                       ((u16)HCI_HOST_BB | 0x0044)
#define HCI_WRITE_INQUIRY_MODE                                      ((u16)HCI_HOST_BB | 0x0045)
#define HCI_READ_PAGE_SCAN_TYPE                                     ((u16)HCI_HOST_BB | 0x0046)
#define HCI_WRITE_PAGE_SCAN_TYPE                                    ((u16)HCI_HOST_BB | 0x0047)
#define HCI_READ_AFH_CHANNEL_CLASS_M                                ((u16)HCI_HOST_BB | 0x0048)
#define HCI_WRITE_AFH_CHANNEL_CLASS_M                               ((u16)HCI_HOST_BB | 0x0049)
#define HCI_READ_ANON_MODE                                          ((u16)HCI_HOST_BB | 0x004A)
#define HCI_WRITE_ANON_MODE                                         ((u16)HCI_HOST_BB | 0x004B)
#define HCI_READ_ALIAS_AUTH_ENABLE                                  ((u16)HCI_HOST_BB | 0x004C)
#define HCI_WRITE_ALIAS_AUTH_ENABLE                                 ((u16)HCI_HOST_BB | 0x004D)
#define HCI_READ_ANON_ADDR_CHANGE_PARAMS                            ((u16)HCI_HOST_BB | 0x004E)
#define HCI_WRITE_ANON_ADDR_CHANGE_PARAMS                           ((u16)HCI_HOST_BB | 0x004F)
#define HCI_RESET_FIXED_ADDRESS_ATTEMPTS_COUNTER                    ((u16)HCI_HOST_BB | 0x0050)
#define HCI_READ_EXTENDED_INQUIRY_RESPONSE_DATA                     ((u16)HCI_HOST_BB | 0x0051)
#define HCI_WRITE_EXTENDED_INQUIRY_RESPONSE_DATA                    ((u16)HCI_HOST_BB | 0x0052)
#define HCI_REFRESH_ENCRYPTION_KEY                                  ((u16)HCI_HOST_BB | 0x0053)
#define HCI_READ_SIMPLE_PAIRING_MODE                                ((u16)HCI_HOST_BB | 0x0055)
#define HCI_WRITE_SIMPLE_PAIRING_MODE                               ((u16)HCI_HOST_BB | 0x0056)
#define HCI_READ_LOCAL_OOB_DATA                                     ((u16)HCI_HOST_BB | 0x0057)
#define HCI_READ_INQUIRY_RESPONSE_TX_POWER_LEVEL                    ((u16)HCI_HOST_BB | 0x0058)
#define HCI_WRITE_INQUIRY_TRANSMIT_POWER_LEVEL                      ((u16)HCI_HOST_BB | 0x0059)
#define HCI_ENHANCED_FLUSH                                          ((u16)HCI_HOST_BB | 0x005F)
#define HCI_SEND_KEYPRESS_NOTIFICATION                              ((u16)HCI_HOST_BB | 0x0060)
#define HCI_SET_EVENT_MASK_PAGE_2                                   ((u16)HCI_HOST_BB | 0x0063)
#define HCI_READ_ENH_TX_POWER_LEVEL                                 ((u16)HCI_HOST_BB | 0x0068)
#define HCI_READ_LE_HOST_SUPPORT                                    ((u16)HCI_HOST_BB | 0x006C)
#define HCI_WRITE_LE_HOST_SUPPORT                                   ((u16)HCI_HOST_BB | 0x006D)
#define HCI_SET_RESERVED_LT_ADDR                                    ((u16)HCI_HOST_BB | 0x0074)
#define HCI_DELETE_RESERVED_LT_ADDR                                 ((u16)HCI_HOST_BB | 0x0075)
#define HCI_SET_CSB_DATA                                            ((u16)HCI_HOST_BB | 0x0076)
#define HCI_READ_SYNCHRONIZATION_TRAIN_PARAMS                       ((u16)HCI_HOST_BB | 0x0077)
#define HCI_WRITE_SYNCHRONIZATION_TRAIN_PARAMS                      ((u16)HCI_HOST_BB | 0x0078)
#define HCI_READ_SECURE_CONNECTIONS_HOST_SUPPORT                    ((u16)HCI_HOST_BB | 0x0079)
#define HCI_WRITE_SECURE_CONNECTIONS_HOST_SUPPORT                   ((u16)HCI_HOST_BB | 0x007A)
#define HCI_READ_AUTHENTICATED_PAYLOAD_TIMEOUT                      ((u16)HCI_HOST_BB | 0x007B)
#define HCI_WRITE_AUTHENTICATED_PAYLOAD_TIMEOUT                     ((u16)HCI_HOST_BB | 0x007C)
#define HCI_READ_LOCAL_OOB_EXTENDED_DATA                            ((u16)HCI_HOST_BB | 0x007D)
#define HCI_READ_LOCAL_VER_INFO                                     ((u16)HCI_INFO | 0x0001)
#define HCI_READ_LOCAL_SUPP_COMMANDS                                ((u16)HCI_INFO | 0x0002)
#define HCI_READ_LOCAL_SUPP_FEATURES                                ((u16)HCI_INFO | 0x0003)
#define HCI_READ_LOCAL_EXT_FEATURES                                 ((u16)HCI_INFO | 0x0004)
#define HCI_READ_BUFFER_SIZE                                        ((u16)HCI_INFO | 0x0005)
#define HCI_READ_COUNTRY_CODE                                       ((u16)HCI_INFO | 0x0007)
#define HCI_READ_BD_ADDR                                            ((u16)HCI_INFO | 0x0009)
#define HCI_READ_LOCAL_SUPP_CODECS                                  ((u16)HCI_INFO | 0x000B)
#define HCI_READ_FAILED_CONTACT_COUNT                               ((u16)HCI_STATUS | 0x0001)
#define HCI_RESET_FAILED_CONTACT_COUNT                              ((u16)HCI_STATUS | 0x0002)
#define HCI_GET_LINK_QUALITY                                        ((u16)HCI_STATUS | 0x0003)
#define HCI_READ_RSSI                                               ((u16)HCI_STATUS | 0x0005)
#define HCI_READ_AFH_CHANNEL_MAP                                    ((u16)HCI_STATUS | 0x0006)
#define HCI_READ_CLOCK                                              ((u16)HCI_STATUS | 0x0007)
#define HCI_READ_ENCRYPTION_KEY_SIZE                                ((u16)HCI_STATUS | 0x0008)
#define HCI_SET_TRIGGERED_CLOCK_CAPTURE                             ((u16)HCI_STATUS | 0x000D)
#define HCI_READ_LOOPBACK_MODE                                      ((u16)HCI_TEST | 0x0001)
#define HCI_WRITE_LOOPBACK_MODE                                     ((u16)HCI_TEST | 0x0002)
#define HCI_ENABLE_DUT_MODE                                         ((u16)HCI_TEST | 0x0003)
#define HCI_WRITE_SIMPLE_PAIRING_DEBUG_MODE                         ((u16)HCI_TEST | 0x0004)
#define HCI_WRITE_SECURE_CONNECTIONS_TEST_MODE                      ((u16)HCI_TEST | 0x000A)
#define HCI_ULP_SET_EVENT_MASK                                      ((u16)HCI_ULP | 0x0001)
#define HCI_ULP_READ_BUFFER_SIZE                                    ((u16)HCI_ULP | 0x0002)
#define HCI_ULP_READ_LOCAL_SUPPORTED_FEATURES                       ((u16)HCI_ULP | 0x0003)
#define HCI_ULP_SET_RANDOM_ADDRESS                                  ((u16)HCI_ULP | 0x0005)
#define HCI_ULP_SET_ADVERTISING_PARAMETERS                          ((u16)HCI_ULP | 0x0006)
#define HCI_ULP_READ_ADVERTISING_CHANNEL_TX_POWER                   ((u16)HCI_ULP | 0x0007)
#define HCI_ULP_SET_ADVERTISING_DATA                                ((u16)HCI_ULP | 0x0008)
#define HCI_ULP_SET_SCAN_RESPONSE_DATA                              ((u16)HCI_ULP | 0x0009)
#define HCI_ULP_SET_ADVERTISE_ENABLE                                ((u16)HCI_ULP | 0x000A)
#define HCI_ULP_SET_SCAN_PARAMETERS                                 ((u16)HCI_ULP | 0x000B)
#define HCI_ULP_SET_SCAN_ENABLE                                     ((u16)HCI_ULP | 0x000C)
#define HCI_ULP_CREATE_CONNECTION                                   ((u16)HCI_ULP | 0x000D)
#define HCI_ULP_CREATE_CONNECTION_CANCEL                            ((u16)HCI_ULP | 0x000E)
#define HCI_ULP_READ_WHITE_LIST_SIZE                                ((u16)HCI_ULP | 0x000F)
#define HCI_ULP_CLEAR_WHITE_LIST                                    ((u16)HCI_ULP | 0x0010)
#define HCI_ULP_ADD_DEVICE_TO_WHITE_LIST                            ((u16)HCI_ULP | 0x0011)
#define HCI_ULP_REMOVE_DEVICE_FROM_WHITE_LIST                       ((u16)HCI_ULP | 0x0012)
#define HCI_ULP_CONNECTION_UPDATE                                   ((u16)HCI_ULP | 0x0013)
#define HCI_ULP_SET_HOST_CHANNEL_CLASSIFICATION                     ((u16)HCI_ULP | 0x0014)
#define HCI_ULP_READ_CHANNEL_MAP                                    ((u16)HCI_ULP | 0x0015)
#define HCI_ULP_READ_REMOTE_USED_FEATURES                           ((u16)HCI_ULP | 0x0016)
#define HCI_ULP_ENCRYPT                                             ((u16)HCI_ULP | 0x0017)
#define HCI_ULP_RAND                                                ((u16)HCI_ULP | 0x0018)
#define HCI_ULP_START_ENCRYPTION                                    ((u16)HCI_ULP | 0x0019)
#define HCI_ULP_LONG_TERM_KEY_REQUEST_REPLY                         ((u16)HCI_ULP | 0x001A)
#define HCI_ULP_LONG_TERM_KEY_REQUEST_NEGATIVE_REPLY                ((u16)HCI_ULP | 0x001B)
#define HCI_ULP_READ_SUPPORTED_STATES                               ((u16)HCI_ULP | 0x001C)
#define HCI_ULP_RECEIVER_TEST                                       ((u16)HCI_ULP | 0x001D)
#define HCI_ULP_TRANSMITTER_TEST                                    ((u16)HCI_ULP | 0x001E)
#define HCI_ULP_TEST_END                                            ((u16)HCI_ULP | 0x001F)
#define HCI_ULP_REMOTE_CONNECTION_PARAMETER_REQUEST_REPLY           ((u16)HCI_ULP | 0x0020)
#define HCI_ULP_REMOTE_CONNECTION_PARAMETER_REQUEST_NEGATIVE_REPLY  ((u16)HCI_ULP | 0x0021)
#define HCI_ULP_SET_DATA_LENGTH                                     ((u16)HCI_ULP | 0x0022)
#define HCI_ULP_READ_SUGGESTED_DEFAULT_DATA_LENGTH                  ((u16)HCI_ULP | 0x0023)
#define HCI_ULP_WRITE_SUGGESTED_DEFAULT_DATA_LENGTH                 ((u16)HCI_ULP | 0x0024)
#define HCI_ULP_READ_LOCAL_P256_PUBLIC_KEY                          ((u16)HCI_ULP | 0x0025)
#define HCI_ULP_GENERATE_DHKEY                                      ((u16)HCI_ULP | 0x0026)
#define HCI_ULP_ADD_DEVICE_TO_RESOLVING_LIST                        ((u16)HCI_ULP | 0x0027)
#define HCI_ULP_REMOVE_DEVICE_FROM_RESOLVING_LIST                   ((u16)HCI_ULP | 0x0028)
#define HCI_ULP_CLEAR_RESOLVING_LIST                                ((u16)HCI_ULP | 0x0029)
#define HCI_ULP_READ_RESOLVING_LIST_SIZE                            ((u16)HCI_ULP | 0x002A)
#define HCI_ULP_READ_PEER_RESOLVABLE_ADDRESS                        ((u16)HCI_ULP | 0x002B)
#define HCI_ULP_READ_LOCAL_RESOLVABLE_ADDRESS                       ((u16)HCI_ULP | 0x002C)
#define HCI_ULP_SET_ADDRESS_RESOLUTION_ENABLE                       ((u16)HCI_ULP | 0x002D)
#define HCI_ULP_SET_RANDOM_PRIVATE_ADDRESS_TIMEOUT                  ((u16)HCI_ULP | 0x002E)
#define HCI_ULP_READ_MAXIMUM_DATA_LENGTH                            ((u16)HCI_ULP | 0x002F)
#define HCI_ULP_READ_PHY                                            ((u16)HCI_ULP | 0x0030)
#define HCI_ULP_SET_DEFAULT_PHY                                     ((u16)HCI_ULP | 0x0031)
#define HCI_ULP_SET_PHY                                             ((u16)HCI_ULP | 0x0032)
#define HCI_ULP_ENHANCED_RECEIVER_TEST                              ((u16)HCI_ULP | 0x0033)
#define HCI_ULP_ENHANCED_TRANSMITTER_TEST                           ((u16)HCI_ULP | 0x0034)

#define HCI_EV_INQUIRY_COMPLETE                      ((u8)0x01)
#define HCI_EV_INQUIRY_RESULT                        ((u8)0x02)
#define HCI_EV_CONN_COMPLETE                         ((u8)0x03)
#define HCI_EV_CONN_REQUEST                          ((u8)0x04)
#define HCI_EV_DISCONNECT_COMPLETE                   ((u8)0x05)
#define HCI_EV_AUTH_COMPLETE                         ((u8)0x06)
#define HCI_EV_REMOTE_NAME_REQ_COMPLETE              ((u8)0x07)
#define HCI_EV_ENCRYPTION_CHANGE                     ((u8)0x08)
#define HCI_EV_CHANGE_CONN_LINK_KEY_COMPLETE         ((u8)0x09)
#define HCI_EV_MASTER_LINK_KEY_COMPLETE              ((u8)0x0A)
#define HCI_EV_READ_REM_SUPP_FEATURES_COMPLETE       ((u8)0x0B)
#define HCI_EV_READ_REMOTE_VER_INFO_COMPLETE         ((u8)0x0C)
#define HCI_EV_QOS_SETUP_COMPLETE                    ((u8)0x0D)
#define HCI_EV_COMMAND_COMPLETE                      ((u8)0x0E)
#define HCI_EV_COMMAND_STATUS                        ((u8)0x0F)
#define HCI_EV_HARDWARE_ERROR                        ((u8)0x10)
#define HCI_EV_FLUSH_OCCURRED                        ((u8)0x11)
#define HCI_EV_ROLE_CHANGE                           ((u8)0x12)
#define HCI_EV_NUMBER_COMPLETED_PKTS                 ((u8)0x13)
#define HCI_EV_MODE_CHANGE                           ((u8)0x14)
#define HCI_EV_RETURN_LINK_KEYS                      ((u8)0x15)
#define HCI_EV_PIN_CODE_REQ                          ((u8)0x16)
#define HCI_EV_LINK_KEY_REQ                          ((u8)0x17)
#define HCI_EV_LINK_KEY_NOTIFICATION                 ((u8)0x18)
#define HCI_EV_LOOPBACK_COMMAND                      ((u8)0x19)
#define HCI_EV_DATA_BUFFER_OVERFLOW                  ((u8)0x1A)
#define HCI_EV_MAX_SLOTS_CHANGE                      ((u8)0x1B)
#define HCI_EV_READ_CLOCK_OFFSET_COMPLETE            ((u8)0x1C)
#define HCI_EV_CONN_PACKET_TYPE_CHANGED              ((u8)0x1D)
#define HCI_EV_QOS_VIOLATION                         ((u8)0x1E)
#define HCI_EV_PAGE_SCAN_MODE_CHANGE                 ((u8)0x1F)
#define HCI_EV_PAGE_SCAN_REP_MODE_CHANGE             ((u8)0x20)
/* 1.2 Events */
#define HCI_EV_FLOW_SPEC_COMPLETE                    ((u8)0x21)
#define HCI_EV_INQUIRY_RESULT_WITH_RSSI              ((u8)0x22)
#define HCI_EV_READ_REM_EXT_FEATURES_COMPLETE        ((u8)0x23)
#define HCI_EV_FIXED_ADDRESS                         ((u8)0x24)
#define HCI_EV_ALIAS_ADDRESS                         ((u8)0x25)
#define HCI_EV_GENERATE_ALIAS_REQ                    ((u8)0x26)
#define HCI_EV_ACTIVE_ADDRESS                        ((u8)0x27)
#define HCI_EV_ALLOW_PRIVATE_PAIRING                 ((u8)0x28)
#define HCI_EV_ALIAS_ADDRESS_REQ                     ((u8)0x29)
#define HCI_EV_ALIAS_NOT_RECOGNISED                  ((u8)0x2A)
#define HCI_EV_FIXED_ADDRESS_ATTEMPT                 ((u8)0x2B)
#define HCI_EV_SYNC_CONN_COMPLETE                    ((u8)0x2C)
#define HCI_EV_SYNC_CONN_CHANGED                     ((u8)0x2D)

/* 2.1 Events */
#define HCI_EV_SNIFF_SUB_RATE                        ((u8)0x2E)
#define HCI_EV_EXTENDED_INQUIRY_RESULT               ((u8)0x2F)
#define HCI_EV_ENCRYPTION_KEY_REFRESH_COMPLETE       ((u8)0x30)
#define HCI_EV_IO_CAPABILITY_REQUEST                 ((u8)0x31)
#define HCI_EV_IO_CAPABILITY_RESPONSE                ((u8)0x32)
#define HCI_EV_USER_CONFIRMATION_REQUEST             ((u8)0x33)
#define HCI_EV_USER_PASSKEY_REQUEST                  ((u8)0x34)
#define HCI_EV_REMOTE_OOB_DATA_REQUEST               ((u8)0x35)
#define HCI_EV_SIMPLE_PAIRING_COMPLETE               ((u8)0x36)
#define HCI_EV_LST_CHANGE                            ((u8)0x38)
#define HCI_EV_ENHANCED_FLUSH_COMPLETE               ((u8)0x39)
#define HCI_EV_USER_PASSKEY_NOTIFICATION             ((u8)0x3B)
#define HCI_EV_KEYPRESS_NOTIFICATION                 ((u8)0x3C)
#define HCI_EV_REM_HOST_SUPPORTED_FEATURES           ((u8)0x3D)
#define HCI_EV_ULP                                   ((u8)0x3E)

/* TCC + CSB Events */
#define HCI_EV_TRIGGERED_CLOCK_CAPTURE               ((u8)0x4E)
#define HCI_EV_SYNCHRONIZATION_TRAIN_COMPLETE        ((u8)0x4F)
#define HCI_EV_SYNCHRONIZATION_TRAIN_RECEIVED        ((u8)0x50)
#define HCI_EV_CSB_RECEIVE                           ((u8)0x51)
#define HCI_EV_CSB_TIMEOUT                           ((u8)0x52)
#define HCI_EV_TRUNCATED_PAGE_COMPLETE               ((u8)0x53)
#define HCI_EV_SLAVE_PAGE_RESPONSE_TIMEOUT           ((u8)0x54)
#define HCI_EV_CSB_CHANNEL_MAP_CHANGE                ((u8)0x55)
#define HCI_EV_INQUIRY_RESPONSE_NOTIFICATION         ((u8)0x56)

/* 4.1 Events */
#define HCI_EV_AUTHENTICATED_PAYLOAD_TIMEOUT_EXPIRED ((u8)0x57)

/* ULP Sub-opcodes */
#define HCI_EV_ULP_CONNECTION_COMPLETE                 ((u8)0x01)
#define HCI_EV_ULP_ADVERTISING_REPORT                  ((u8)0x02)
#define HCI_EV_ULP_CONNECTION_UPDATE_COMPLETE          ((u8)0x03)
#define HCI_EV_ULP_READ_REMOTE_USED_FEATURES_COMPLETE  ((u8)0x04)
#define HCI_EV_ULP_LONG_TERM_KEY_REQUEST               ((u8)0x05)
#define HCI_EV_ULP_REMOTE_CONNECTION_PARAMETER_REQUEST ((u8)0x06)
#define HCI_EV_ULP_DATA_LENGTH_CHANGE                  ((u8)0x07)
#define HCI_EV_ULP_READ_LOCAL_P256_PUB_KEY_COMPLETE    ((u8)0x08)
#define HCI_EV_ULP_GENERATE_DHKEY_COMPLETE             ((u8)0x09)
#define HCI_EV_ULP_ENHANCED_CONNECTION_COMPLETE        ((u8)0x0A)
#define HCI_EV_ULP_DIRECT_ADVERTISING_REPORT           ((u8)0x0B)
#define HCI_EV_ULP_PHY_UPDATE_COMPLETE                 ((u8)0x0C)
/* The subevent code of ULP_USED_CHANNEL_SELECTION_EVENT shall be updated
   when it is defined in the spec.
   Assign it as 0x0D temporarily.                                     */
#define HCI_EV_ULP_USED_CHANNEL_SELECTION              ((u8)0x0D)

#define HCI_CMD_DECODE(entry) case entry: ret = #entry; break
#define HCI_EV_DECODE(entry) case entry: ret = #entry; break

#endif /* __SCSC_BT_HCI_H */
